# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PIG 构建action

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: mvn clean install
      run: mvn clean install

    - name: mvn spring-javaformat:validate
      run: mvn spring-javaformat:validate

    - name: success
      if:  success() && github.repository == 'pig-mesh/pig'
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
      with:
        msgtype: markdown
        content: |
          # 💯👨‍💻 Success 🎉🎉🎉
          > Github Action: https://github.com/pig-mesh/pig success
          > ^_^ from github action message

    - name:  failure
      if: failure() && github.repository == 'pig-mesh/pig'
      uses: chf007/action-wechat-work@master
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
      with:
        msgtype: markdown
        content: |
          # 💤🤷‍♀️ failure 🙅‍♂️💣
          > Github Action: https://github.com/pig-mesh/pig failure
          > (⋟﹏⋞)   from github action message
