# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PIG 代码同步至 gitee

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: sync-gitee-mirror
        if: github.repository == 'pig-mesh/pig'
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: log4j/pig
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}

